language: c++
before_cache:
  - ccache -s
cache: ccache
before_install:
  - sudo apt-get -qq update
  - curl https://sh.rustup.rs -sSf > rustup.sh
  - chmod +x rustup.sh
  - ./rustup.sh -y
  - source ~/.cargo/env
install:
  - cargo build -vv
  - make assets
script:
  - cargo test -- --nocapture
